import "server-only";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import type { DocumentKind, JobRecord } from "@/lib/types/assessment";

/**
 * Jobs live on the local filesystem under the OS temp dir.
 *
 * Why disk and not a module-level Map: Next.js recreates module scope on hot
 * reload in dev and across route handlers in some deployment targets, which
 * silently loses in-flight jobs. `os.tmpdir()` is writable both locally and on
 * serverless platforms, needs no database, and survives module reloads.
 * A short TTL sweep keeps it from growing without bound.
 */

const ROOT = path.join(os.tmpdir(), "vedaai-jobs");
const TTL_MS = 60 * 60 * 1000; // 1 hour

function jobDir(jobId: string): string {
  // jobIds are generated by us (hex), but never trust a path segment blindly.
  const safe = jobId.replace(/[^a-zA-Z0-9_-]/g, "");
  if (!safe) throw new Error("Invalid job id");
  return path.join(ROOT, safe);
}

function pageFile(jobId: string, kind: DocumentKind, pageNumber: number): string {
  return path.join(jobDir(jobId), `${kind}-${pageNumber}.png`);
}

export async function createJobDir(jobId: string): Promise<void> {
  await fs.mkdir(jobDir(jobId), { recursive: true });
}

export async function writeJob(record: JobRecord): Promise<void> {
  await createJobDir(record.id);
  const file = path.join(jobDir(record.id), "job.json");
  const tmp = `${file}.${process.pid}.tmp`;
  // Write-then-rename so a concurrent poll never reads a half-written file.
  await fs.writeFile(tmp, JSON.stringify(record), "utf8");
  await fs.rename(tmp, file);
}

export async function readJob(jobId: string): Promise<JobRecord | null> {
  try {
    const raw = await fs.readFile(path.join(jobDir(jobId), "job.json"), "utf8");
    return JSON.parse(raw) as JobRecord;
  } catch {
    return null;
  }
}

export async function writePageImage(
  jobId: string,
  kind: DocumentKind,
  pageNumber: number,
  png: Buffer,
): Promise<void> {
  await createJobDir(jobId);
  await fs.writeFile(pageFile(jobId, kind, pageNumber), png);
}

export async function readPageImage(
  jobId: string,
  kind: DocumentKind,
  pageNumber: number,
): Promise<Buffer | null> {
  try {
    return await fs.readFile(pageFile(jobId, kind, pageNumber));
  } catch {
    return null;
  }
}

/** Remove job directories older than the TTL. Best-effort, never throws. */
export async function sweepExpiredJobs(): Promise<void> {
  try {
    const entries = await fs.readdir(ROOT, { withFileTypes: true });
    const now = Date.now();
    await Promise.all(
      entries
        .filter((entry) => entry.isDirectory())
        .map(async (entry) => {
          const dir = path.join(ROOT, entry.name);
          try {
            const stat = await fs.stat(dir);
            if (now - stat.mtimeMs > TTL_MS) {
              await fs.rm(dir, { recursive: true, force: true });
            }
          } catch {
            /* another process may have removed it already */
          }
        }),
    );
  } catch {
    /* root does not exist yet */
  }
}
